<a href="https://colab.research.google.com/github/27priyanshu/Tensorflow-/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

tf.__version__


'2.14.0'

In [2]:
if tf.test.is_gpu_available():
  print("Running on GPU")
else:
  print("Running on CPU ")

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


Running on GPU


In [3]:
ineuron = tf.constant(30)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [4]:
ineuron_x = tf.constant([[3,5],[5,2]])
print(ineuron_x)

tf.Tensor(
[[3 5]
 [5 2]], shape=(2, 2), dtype=int32)


In [5]:
ineuron_x.numpy()

array([[3, 5],
       [5, 2]], dtype=int32)

Commanly used method is to generate constant tf.one and constant tf.zeros

In [6]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [7]:
print(tf.zeros(shape=(3,5)))

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(3, 5), dtype=float32)


In [8]:
const2 = tf.constant([[2,3,4],[2,3,5]])
const1 = tf.constant([[6,6,3],[1,2,6]])

result = tf.add(const2,const1)
print(result)

tf.Tensor(
[[ 8  9  7]
 [ 3  5 11]], shape=(2, 3), dtype=int32)


In [9]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.10752921,  0.54069126],
       [-1.1289083 , -0.29858506]], dtype=float32)>

In [10]:
tf.random.uniform(shape=(3,3),minval=1,maxval=20,dtype =tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  6],
       [ 6,  4, 10],
       [ 4,  2,  7]], dtype=int32)>

**VARIABLES**

In [11]:
var = 23 #Python
var1 = tf.Variable(42)
var2 = tf.Variable([[[2,3,4],[3,67,8]],[[2,5,8],[87,3,2]]])
var,var1,var2

(23,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
 array([[[ 2,  3,  4],
         [ 3, 67,  8]],
 
        [[ 2,  5,  8],
         [87,  3,  2]]], dtype=int32)>)

Shaping the Tensor

In [12]:
tensor = tf.Variable([[[2,3,4],[3,67,8]],[[2,5,8],[87,3,2]]])
print(tensor.shape)

(2, 2, 3)


In [13]:
tensor1 = tf.reshape(tensor,[2,6])
tensor2 = tf.reshape(tensor,[1,12])

In [14]:
tensor1
# tensor2

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 2,  3,  4,  3, 67,  8],
       [ 2,  5,  8, 87,  3,  2]], dtype=int32)>

Ranking Of tensor

In [15]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 2,  3,  4],
        [ 3, 67,  8]],

       [[ 2,  5,  8],
        [87,  3,  2]]], dtype=int32)>

In [16]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [17]:
tensor3 = tensor[1,0,2] #slice = 1, row = 0, column = 2
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=8>

## Tensorflow Mathmatical Operation

In [22]:
a = tf.random.normal(shape = (2,2))
b = tf.random.normal(shape = (2,2))
c = a+b
d = tf.math.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 1.6701436   0.50068915]
 [-0.6416764   0.6771303 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.13930607  0.12422695]
 [-1.8418226  -0.58830374]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.5308375   0.6249161 ]
 [-2.483499    0.08882654]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2.3434637  0.3905201 ]
 [6.1677675  0.00789015]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4.6220465  1.8680892 ]
 [0.08345071 1.092891  ]], shape=(2, 2), dtype=float32)


## Declaring Ragged Tensors

In [30]:
ragged = tf.ragged.constant([[2,3,5],[8,9],[],[2,21,5]])

print(ragged)
print(ragged[0,:])
print(ragged[1:])

<tf.RaggedTensor [[2, 3, 5], [8, 9], [], [2, 21, 5]]>
tf.Tensor([2 3 5], shape=(3,), dtype=int32)
<tf.RaggedTensor [[8, 9], [], [2, 21, 5]]>


## Finding Sqaure Difference

In [32]:
varx = [1,2,4,5,9]
vary = 5

varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  1,  0, 16], dtype=int32)>