<a href="https://colab.research.google.com/github/27priyanshu/Tenshorflow-/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

tf.__version__


'2.14.0'

In [2]:
if tf.test.is_gpu_available():
  print("Running on GPU")
else:
  print("Running on CPU ")

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


Running on GPU


In [4]:
ineuron = tf.constant(30)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [6]:
ineuron_x = tf.constant([[3,5],[5,2]])
print(ineuron_x)

tf.Tensor(
[[3 5]
 [5 2]], shape=(2, 2), dtype=int32)


In [7]:
ineuron_x.numpy()

array([[3, 5],
       [5, 2]], dtype=int32)

Commanly used method is to generate constant tf.one and constant tf.zeros

In [9]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [11]:
print(tf.zeros(shape=(3,5)))

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(3, 5), dtype=float32)


In [16]:
const2 = tf.constant([[2,3,4],[2,3,5]])
const1 = tf.constant([[6,6,3],[1,2,6]])

result = tf.add(const2,const1)
print(result)

tf.Tensor(
[[ 8  9  7]
 [ 3  5 11]], shape=(2, 3), dtype=int32)
